
<!-- Generated by ai2html v0.100.0 - 2025-03-16 15:50 -->
<!-- ai file: feeding_scatter.ai -->
<style lang="scss">
	#g-feeding_scatter-box ,
	#g-feeding_scatter-box .g-artboard {
		margin:0 auto;
	}
	#g-feeding_scatter-box p {
		margin:0;
	}
	#g-feeding_scatter-box .g-aiAbs {
		position:absolute;
	}
	#g-feeding_scatter-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-feeding_scatter-box .g-aiPointText p { white-space: nowrap; }
	#g-feeding_scatter-640 {
		position:relative;
		overflow:hidden;
	}
	#g-feeding_scatter-640 p {
		font-weight:400;
		line-height:14px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:12px;
		text-align:left;
		color:rgb(0,0,0);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-feeding_scatter-640 .g-pstyle0 {
		height:14px;
	}
	#g-feeding_scatter-480 {
		position:relative;
		overflow:hidden;
	}
	#g-feeding_scatter-320 {
		position:relative;
		overflow:hidden;
	}

	/* Custom CSS */


</style>

<div id="g-feeding_scatter-box" bind:clientWidth={width}>

	<!-- Artboard: 640 -->
{#if width && (width >= 640)}	<div id="g-feeding_scatter-640" class="g-artboard" style="">
<div style="padding: 0 0 62.5% 0;"></div>
		<div id="g-feeding_scatter-640-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath }/feeding_scatter-640.png);"></div>		<div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.3805%;margin-top:-7.5px;left:38.2%;width:64px;">
			<p class="g-pstyle0">TESTING</p>
		</div>
	</div>
{/if}
	<!-- Artboard: 480 -->
{#if width && ( width >= 480 && width <640)}	<div id="g-feeding_scatter-480" class="g-artboard" style="">
<div style="padding: 0 0 83.3333% 0;"></div>
		<div id="g-feeding_scatter-480-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath }/feeding_scatter-480.png);"></div>	</div>
{/if}
	<!-- Artboard: 320 -->
{#if width && ( width >= 0 && width <480)}	<div id="g-feeding_scatter-320" class="g-artboard" style="">
<div style="padding: 0 0 125% 0;"></div>
		<div id="g-feeding_scatter-320-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath }/feeding_scatter-320.png);"></div>	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2025-03-16 15:50 -->
