
<!-- Generated by ai2html v0.100.0 - 2025-06-14 14:44 -->
<!-- ai file: feeding_scatter.ai -->
<style lang="scss">
	#g-feeding_scatter-box ,
	#g-feeding_scatter-box .g-artboard {
		margin:0 auto;
	}
	#g-feeding_scatter-box p {
		margin:0;
	}
	#g-feeding_scatter-box .g-aiAbs {
		position:absolute;
	}
	#g-feeding_scatter-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-feeding_scatter-box .g-aiPointText p { white-space: nowrap; }
	#g-feeding_scatter-640 {
		position:relative;
		overflow:hidden;
	}
	#g-feeding_scatter-640 p {
		font-weight:400;
		font-style:normal;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(71,71,71);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		position:static;
	}
	#g-feeding_scatter-640 .g-pstyle0 {
		line-height:19px;
		height:19px;
		font-size:16px;
		color:rgb(63,63,63);
	}
	#g-feeding_scatter-640 .g-pstyle1 {
		line-height:19px;
		height:19px;
		font-size:16px;
		text-align:right;
		color:rgb(24,108,232);
	}
	#g-feeding_scatter-640 .g-pstyle2 {
		line-height:19px;
		height:19px;
		font-size:16px;
		text-align:right;
	}
	#g-feeding_scatter-640 .g-pstyle3 {
		font-style:italic;
		height:17px;
	}
	#g-feeding_scatter-640 .g-pstyle4 {
		line-height:19px;
		height:19px;
		font-size:16px;
		text-align:center;
	}
	#g-feeding_scatter-480 {
		position:relative;
		overflow:hidden;
	}
	#g-feeding_scatter-480 p {
		font-weight:400;
		font-style:normal;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(71,71,71);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		position:static;
	}
	#g-feeding_scatter-480 .g-pstyle0 {
		height:17px;
		color:rgb(63,63,63);
	}
	#g-feeding_scatter-480 .g-pstyle1 {
		height:17px;
		text-align:right;
		color:rgb(24,108,232);
	}
	#g-feeding_scatter-480 .g-pstyle2 {
		height:17px;
		text-align:right;
	}
	#g-feeding_scatter-480 .g-pstyle3 {
		font-style:italic;
		height:17px;
	}
	#g-feeding_scatter-480 .g-pstyle4 {
		height:17px;
		text-align:center;
	}
	#g-feeding_scatter-320 {
		position:relative;
		overflow:hidden;
	}
	#g-feeding_scatter-320 p {
		font-weight:400;
		font-style:normal;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(71,71,71);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		position:static;
	}
	#g-feeding_scatter-320 .g-pstyle0 {
		height:17px;
		color:rgb(63,63,63);
	}
	#g-feeding_scatter-320 .g-pstyle1 {
		height:17px;
		text-align:right;
		color:rgb(24,108,232);
	}
	#g-feeding_scatter-320 .g-pstyle2 {
		height:17px;
		text-align:right;
	}
	#g-feeding_scatter-320 .g-pstyle3 {
		font-style:italic;
		height:17px;
	}
	#g-feeding_scatter-320 .g-pstyle4 {
		height:17px;
		text-align:center;
	}

	/* Custom CSS */


</style>

<div id="g-feeding_scatter-box" bind:clientWidth={width}>

	<!-- Artboard: 640 -->
{#if width && (width >= 640)}	<div id="g-feeding_scatter-640" class="g-artboard" style="">
<div style="padding: 0 0 58.6356% 0;"></div>
		<div id="g-feeding_scatter-640-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath }/feeding_scatter-640.png);"></div>		<div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:3.7978%;margin-top:-10.3px;left:21.4103%;width:134px;">
			<p class="g-pstyle0">Breast feedings</p>
		</div>
		<div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:3.7978%;margin-top:-10.3px;right:39.0388%;width:131px;">
			<p class="g-pstyle1">Bottle feedings</p>
		</div>
		<div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.6603%;margin-top:-10.3px;right:90.1697%;width:85px;">
			<p class="g-pstyle2">Midnight</p>
		</div>
		<div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:13.3659%;margin-top:-9.2px;left:30.8819%;width:192px;">
			<p class="g-pstyle3">When humans should sleep</p>
		</div>
		<div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:30.9784%;margin-top:-10.3px;right:90.2559%;width:58px;">
			<p class="g-pstyle2">6 PM</p>
		</div>
		<div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:51.4971%;margin-top:-10.3px;right:90.2959%;width:60px;">
			<p class="g-pstyle2">Noon</p>
		</div>
		<div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:72.0158%;margin-top:-10.3px;right:90.1872%;width:59px;">
			<p class="g-pstyle2">6 AM</p>
		</div>
		<div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:80.7845%;margin-top:-9.2px;left:30.8819%;width:192px;">
			<p class="g-pstyle3">When humans should sleep</p>
		</div>
		<div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.9356%;margin-top:-10.3px;right:90.1697%;width:85px;">
			<p class="g-pstyle2">Midnight</p>
		</div>
		<div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.7981%;margin-top:-10.3px;left:11.7319%;margin-left:-16px;width:32px;">
			<p class="g-pstyle4">0</p>
		</div>
		<div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.7981%;margin-top:-10.3px;left:39.4554%;margin-left:-20.5px;width:41px;">
			<p class="g-pstyle4">30</p>
		</div>
		<div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.7981%;margin-top:-10.3px;left:67.2256%;margin-left:-20.5px;width:41px;">
			<p class="g-pstyle4">60</p>
		</div>
		<div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.7981%;margin-top:-10.3px;left:94.9777%;margin-left:-39px;width:78px;">
			<p class="g-pstyle4">90 days</p>
		</div>
	</div>
{/if}
	<!-- Artboard: 480 -->
{#if width && ( width >= 440 && width <640)}	<div id="g-feeding_scatter-480" class="g-artboard" style="">
<div style="padding: 0 0 90.9091% 0;"></div>
		<div id="g-feeding_scatter-480-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath }/feeding_scatter-480.png);"></div>		<div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:3.5394%;margin-top:-9.2px;left:27.0837%;width:120px;">
			<p class="g-pstyle0">Breast feedings</p>
		</div>
		<div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:3.5394%;margin-top:-9.2px;right:5.0673%;width:117px;">
			<p class="g-pstyle1">Bottle feedings</p>
		</div>
		<div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.2896%;margin-top:-9.2px;right:87.2615%;width:77px;">
			<p class="g-pstyle2">Midnight</p>
		</div>
		<div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:12.5394%;margin-top:-9.2px;left:30.2437%;width:192px;">
			<p class="g-pstyle3">When humans should sleep</p>
		</div>
		<div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.2894%;margin-top:-9.2px;right:87.2293%;width:54px;">
			<p class="g-pstyle2">6 PM</p>
		</div>
		<div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:48.5394%;margin-top:-9.2px;right:87.2234%;width:56px;">
			<p class="g-pstyle2">Noon</p>
		</div>
		<div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.5396%;margin-top:-9.2px;right:87.3407%;width:54px;">
			<p class="g-pstyle2">6 AM</p>
		</div>
		<div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:75.7894%;margin-top:-9.2px;left:30.2437%;width:192px;">
			<p class="g-pstyle3">When humans should sleep</p>
		</div>
		<div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:85.5394%;margin-top:-9.2px;right:87.2615%;width:77px;">
			<p class="g-pstyle2">Midnight</p>
		</div>
		<div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.2894%;margin-top:-9.2px;left:14.4738%;margin-left:-15px;width:30px;">
			<p class="g-pstyle4">0</p>
		</div>
		<div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.2894%;margin-top:-9.2px;left:40.927%;margin-left:-19.5px;width:39px;">
			<p class="g-pstyle4">30</p>
		</div>
		<div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.2894%;margin-top:-9.2px;left:67.3119%;margin-left:-19.5px;width:39px;">
			<p class="g-pstyle4">60</p>
		</div>
		<div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:90.2894%;margin-top:-9.2px;left:93.6312%;margin-left:-35.5px;width:71px;">
			<p class="g-pstyle4">90 days</p>
		</div>
	</div>
{/if}
	<!-- Artboard: 320 -->
{#if width && ( width >= 0 && width <440)}	<div id="g-feeding_scatter-320" class="g-artboard" style="">
<div style="padding: 0 0 125% 0;"></div>
		<div id="g-feeding_scatter-320-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath }/feeding_scatter-320.png);"></div>		<div id="g-ai2-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:3.7894%;margin-top:-9.2px;left:25.6528%;width:120px;">
			<p class="g-pstyle0">Breast feedings</p>
		</div>
		<div id="g-ai2-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:3.7894%;margin-top:-9.2px;right:5.8109%;width:117px;">
			<p class="g-pstyle1">Bottle feedings</p>
		</div>
		<div id="g-ai2-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:9.7894%;margin-top:-9.2px;right:82.2646%;width:77px;">
			<p class="g-pstyle2">Midnight</p>
		</div>
		<div id="g-ai2-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:13.5394%;margin-top:-9.2px;left:34.4815%;width:192px;">
			<p class="g-pstyle3">When humans should sleep</p>
		</div>
		<div id="g-ai2-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:31.2896%;margin-top:-9.2px;right:82.2202%;width:54px;">
			<p class="g-pstyle2">6 PM</p>
		</div>
		<div id="g-ai2-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:52.0396%;margin-top:-9.2px;right:82.2121%;width:56px;">
			<p class="g-pstyle2">Noon</p>
		</div>
		<div id="g-ai2-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:72.5396%;margin-top:-9.2px;right:82.3734%;width:54px;">
			<p class="g-pstyle2">6 AM</p>
		</div>
		<div id="g-ai2-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:81.2894%;margin-top:-9.2px;left:34.4815%;width:192px;">
			<p class="g-pstyle3">When humans should sleep</p>
		</div>
		<div id="g-ai2-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:91.7896%;margin-top:-9.2px;right:82.2646%;width:77px;">
			<p class="g-pstyle2">Midnight</p>
		</div>
		<div id="g-ai2-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.0394%;margin-top:-9.2px;left:20.1896%;margin-left:-15px;width:30px;">
			<p class="g-pstyle4">0</p>
		</div>
		<div id="g-ai2-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.0394%;margin-top:-9.2px;left:44.1598%;margin-left:-19.5px;width:39px;">
			<p class="g-pstyle4">30</p>
		</div>
		<div id="g-ai2-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.0394%;margin-top:-9.2px;left:68.0361%;margin-left:-19.5px;width:39px;">
			<p class="g-pstyle4">60</p>
		</div>
		<div id="g-ai2-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:97.0394%;margin-top:-9.2px;left:91.8222%;margin-left:-35.5px;width:71px;">
			<p class="g-pstyle4">90 days</p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2025-06-14 14:44 -->
