
<!-- Generated by ai2html v0.100.0 - 2025-04-05 18:02 -->
<!-- ai file: photo_chart.ai -->
<style lang="scss">
	#g-photo_chart-box ,
	#g-photo_chart-box .g-artboard {
		margin:0 auto;
	}
	#g-photo_chart-box p {
		margin:0;
	}
	#g-photo_chart-box .g-aiAbs {
		position:absolute;
	}
	#g-photo_chart-box .g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
		height: 100%;
		background-size: contain;
		background-repeat: no-repeat;
	}
	#g-photo_chart-box .g-aiPointText p { white-space: nowrap; }
	#g-photo_chart-640 {
		position:relative;
		overflow:hidden;
	}
	#g-photo_chart-640 p {
		font-weight:400;
		line-height:19px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:16px;
		text-align:left;
		color:rgb(71,71,71);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-photo_chart-640 .g-pstyle0 {
		height:19px;
		text-align:right;
	}
	#g-photo_chart-640 .g-pstyle1 {
		height:19px;
	}
	#g-photo_chart-640 .g-pstyle2 {
		font-weight:600;
		height:19px;
		color:rgb(178,82,146);
	}
	#g-photo_chart-640 .g-pstyle3 {
		font-weight:600;
		height:19px;
		color:rgb(149,205,139);
	}
	#g-photo_chart-640 .g-pstyle4 {
		font-weight:600;
		height:19px;
		color:rgb(100,158,89);
	}
	#g-photo_chart-640 .g-pstyle5 {
		height:19px;
		text-align:center;
	}
	#g-photo_chart-300 {
		position:relative;
		overflow:hidden;
	}
	#g-photo_chart-300 p {
		font-weight:400;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:14px;
		text-align:left;
		color:rgb(71,71,71);
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
		position:static;
	}
	#g-photo_chart-300 .g-pstyle0 {
		height:17px;
		text-align:right;
	}
	#g-photo_chart-300 .g-pstyle1 {
		height:17px;
	}
	#g-photo_chart-300 .g-pstyle2 {
		font-weight:600;
		height:17px;
		color:rgb(178,82,146);
	}
	#g-photo_chart-300 .g-pstyle3 {
		font-weight:600;
		height:17px;
		color:rgb(149,205,139);
	}
	#g-photo_chart-300 .g-pstyle4 {
		font-weight:600;
		height:17px;
		color:rgb(100,158,89);
	}
	#g-photo_chart-300 .g-pstyle5 {
		height:17px;
		text-align:center;
	}

	/* Custom CSS */


</style>

<div id="g-photo_chart-box" bind:clientWidth={width}>

	<!-- Artboard: 640 -->
{#if width && (width >= 640)}	<div id="g-photo_chart-640" class="g-artboard" style="">
<div style="padding: 0 0 53.8854% 0;"></div>
		<div id="g-photo_chart-640-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath }/photo_chart-640.png);"></div>		<div id="g-ai0-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.2925%;margin-top:-10.3px;right:93.8226%;width:60px;">
			<p class="g-pstyle0">1000</p>
		</div>
		<div id="g-ai0-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.2925%;margin-top:-10.3px;left:7.232%;width:182px;">
			<p class="g-pstyle1">photos taken by Dad</p>
		</div>
		<div id="g-ai0-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:22.4005%;margin-top:-10.3px;right:93.7289%;width:51px;">
			<p class="g-pstyle0">800</p>
		</div>
		<div id="g-ai0-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:24.769%;margin-top:-10.4px;left:89.0998%;width:64px;">
			<p class="g-pstyle2">KID 1</p>
		</div>
		<div id="g-ai0-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:29.6497%;margin-top:-10.3px;left:89.3233%;width:51px;">
			<p class="g-pstyle1">703</p>
		</div>
		<div id="g-ai0-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.5086%;margin-top:-10.3px;right:93.7289%;width:51px;">
			<p class="g-pstyle0">600</p>
		</div>
		<div id="g-ai0-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.7767%;margin-top:-10.4px;left:89.0998%;width:91px;">
			<p class="g-pstyle3">KID 2 + 1</p>
		</div>
		<div id="g-ai0-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:49.6574%;margin-top:-10.3px;left:89.0676%;width:51px;">
			<p class="g-pstyle1">507</p>
		</div>
		<div id="g-ai0-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:56.6167%;margin-top:-10.3px;right:93.7289%;width:51px;">
			<p class="g-pstyle0">400</p>
		</div>
		<div id="g-ai0-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:59.8551%;margin-top:-10.4px;left:89.0998%;width:64px;">
			<p class="g-pstyle4">KID 2</p>
		</div>
		<div id="g-ai0-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:64.7357%;margin-top:-10.3px;left:89.2285%;width:51px;">
			<p class="g-pstyle1">370</p>
		</div>
		<div id="g-ai0-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:74.0147%;margin-top:-10.3px;right:93.7289%;width:51px;">
			<p class="g-pstyle0">200</p>
		</div>
		<div id="g-ai0-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:89.9629%;margin-top:-10.3px;right:93.8052%;width:32px;">
			<p class="g-pstyle0">0</p>
		</div>
		<div id="g-ai0-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.1823%;margin-top:-10.3px;left:11.3318%;margin-left:-16px;width:32px;">
			<p class="g-pstyle5">0</p>
		</div>
		<div id="g-ai0-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.1823%;margin-top:-10.3px;left:23.882%;margin-left:-20.5px;width:41px;">
			<p class="g-pstyle5">30</p>
		</div>
		<div id="g-ai0-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.1823%;margin-top:-10.3px;left:36.4791%;margin-left:-20.5px;width:41px;">
			<p class="g-pstyle5">60</p>
		</div>
		<div id="g-ai0-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.1823%;margin-top:-10.3px;left:49.0763%;margin-left:-20.5px;width:41px;">
			<p class="g-pstyle5">90</p>
		</div>
		<div id="g-ai0-18" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.1823%;margin-top:-10.3px;left:61.7045%;margin-left:-25.5px;width:51px;">
			<p class="g-pstyle5">120</p>
		</div>
		<div id="g-ai0-19" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.1823%;margin-top:-10.3px;left:74.3017%;margin-left:-25.5px;width:51px;">
			<p class="g-pstyle5">150</p>
		</div>
		<div id="g-ai0-20" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:95.1823%;margin-top:-10.3px;left:86.8806%;margin-left:-44px;width:88px;">
			<p class="g-pstyle5">180 days</p>
		</div>
	</div>
{/if}
	<!-- Artboard: 300 -->
{#if width && ( width >= 0 && width <640)}	<div id="g-photo_chart-300" class="g-artboard" style="">
<div style="padding: 0 0 113.4647% 0;"></div>
		<div id="g-photo_chart-300-img" class="g-aiImg" alt="" style="background-image: url({ assetsPath }/photo_chart-300.png);"></div>		<div id="g-ai1-1" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.3345%;margin-top:-9.2px;right:88.2255%;width:56px;">
			<p class="g-pstyle0">1000</p>
		</div>
		<div id="g-ai1-2" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:5.3345%;margin-top:-9.2px;left:12.9692%;width:151px;">
			<p class="g-pstyle1">photos taken by Dad</p>
		</div>
		<div id="g-ai1-3" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:15.0723%;margin-top:-9.3px;left:79.086%;width:59px;">
			<p class="g-pstyle2">KID 1</p>
		</div>
		<div id="g-ai1-4" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:20.0233%;margin-top:-9.2px;left:79.296%;width:47px;">
			<p class="g-pstyle1">703</p>
		</div>
		<div id="g-ai1-5" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:22.9611%;margin-top:-9.2px;right:88.4255%;width:47px;">
			<p class="g-pstyle0">800</p>
		</div>
		<div id="g-ai1-6" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:39.162%;margin-top:-9.3px;left:79.086%;width:82px;">
			<p class="g-pstyle3">KID 2 + 1</p>
		</div>
		<div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:40.2939%;margin-top:-9.2px;right:88.4255%;width:47px;">
			<p class="g-pstyle0">600</p>
		</div>
		<div id="g-ai1-8" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:44.1131%;margin-top:-9.2px;left:79.0559%;width:47px;">
			<p class="g-pstyle1">507</p>
		</div>
		<div id="g-ai1-9" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:57.6268%;margin-top:-9.2px;right:88.4255%;width:47px;">
			<p class="g-pstyle0">400</p>
		</div>
		<div id="g-ai1-10" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:69.7147%;margin-top:-9.3px;left:79.2724%;width:59px;">
			<p class="g-pstyle4">KID 2</p>
		</div>
		<div id="g-ai1-11" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:74.6659%;margin-top:-9.2px;left:79.3933%;width:47px;">
			<p class="g-pstyle1">370</p>
		</div>
		<div id="g-ai1-12" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:74.9597%;margin-top:-9.2px;right:88.4255%;width:47px;">
			<p class="g-pstyle0">200</p>
		</div>
		<div id="g-ai1-13" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:91.4112%;margin-top:-9.2px;right:88.5933%;width:30px;">
			<p class="g-pstyle0">0</p>
		</div>
		<div id="g-ai1-14" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.699%;margin-top:-9.2px;left:16.2556%;margin-left:-15px;width:30px;">
			<p class="g-pstyle5">0</p>
		</div>
		<div id="g-ai1-15" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.699%;margin-top:-9.2px;left:40.0113%;margin-left:-19.5px;width:39px;">
			<p class="g-pstyle5">60</p>
		</div>
		<div id="g-ai1-16" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.699%;margin-top:-9.2px;left:63.6007%;margin-left:-23.5px;width:47px;">
			<p class="g-pstyle5">120</p>
		</div>
		<div id="g-ai1-17" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:96.699%;margin-top:-9.2px;left:87.3266%;margin-left:-40px;width:80px;">
			<p class="g-pstyle5">180 days</p>
		</div>
	</div>
{/if}
</div>

<script>
	export let assetsPath = './';
	let width = null;
import { onMount } from 'svelte';
export let onAiMounted = () => {};
onMount(() => {
  onAiMounted();
});

</script>
<!-- End ai2html - 2025-04-05 18:02 -->
